name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build-type: [debug]

        include:

        - os: ubuntu-latest
          build-type: debug
          toolchain: {compiler: gcc, version: '12', mkl_version: '2024.1', build: fpm}

    defaults:
      run:
        shell: bash

    steps:
      - name: Intel Apt repository
        timeout-minutes: 1
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          rm GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update
          
      - name: Install Intel oneAPI compilers
        timeout-minutes: 5
        run: sudo apt-get install intel-oneapi-compiler-fortran intel-oneapi-compiler-dpcpp-cpp 

      # optional
      - name: Install Intel MPI and MKL
        timeout-minutes: 5
        run: intel-oneapi-mpi intel-oneapi-mpi-devel intel-oneapi-mkl

      - name: Setup Intel oneAPI environment
        run: |
          source /opt/intel/oneapi/setvars.sh
          printenv >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install fpm
        uses: fortran-lang/setup-fpm@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install GCC Compiler
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Setup environment for Fortran and C compilers
        run: |
            FC="gfortran"
            CC="gcc"
            CXX="g++"
            echo "FC=$FC" >> $GITHUB_ENV
            echo "CC=$CC" >> $GITHUB_ENV
            echo "CXX=$CXX" >> $GITHUB_ENV

      - name: Build library (fpm)
        run: |
          FPM_CXXFLAGS=-DW_MKL
          echo "FPM_CXXFLAGS=$FPM_CXXFLAGS" >> $GITHUB_ENV
          fpm --version
          fpm build

      - name: Run unit tests (fpm)
        run: fpm test