name: CI

on: [push, pull_request]

env:
  BUILD_DIR: _build
  PIP_PACKAGES: >-
    meson!=1.8.0
    cmake
    ninja
    gcovr
  PIP_EXTRAS: >-
    pkgconfig
    pytest
    pytest-cov
    cffi
    numpy
    ase
    matplotlib
    qcelemental

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        build-type: [debug]
        toolchain:
          - {compiler: gcc, version: '12', build: meson}
          - {compiler: gcc, version: '12', build: cmake}

        include:

        - os: ubuntu-latest
          build-type: debug
          toolchain: {compiler: gcc, version: '12', mkl_version: '2024.1', build: fpm}

        # - os: windows-latest
        #   build: meson
        #   build-type: debug
        #   compiler: gcc
        #   shell: msys2 {0}

    defaults:
      run:
        shell: bash

    env:

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install fpm
      if: ${{ matrix.toolchain.build == 'fpm' }}
      uses: fortran-lang/setup-fpm@v7  # fpm 0.11.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Prepare for cache restore
      if: ${{ matrix.toolchain.build == 'fpm' }}
      run: |
        sudo mkdir -p /opt/intel
        sudo chown $USER /opt/intel

    - name: Cache Intel installation
      if: ${{ matrix.toolchain.build == 'fpm' }}
      id: cache-install
      uses: actions/cache@v4
      with:
        path: /opt/intel/oneapi
        key: install-${{ matrix.toolchain.compiler }}-${{ matrix.toolchain.version }}-${{ matrix.toolchain.mkl_version }}-${{ matrix.os }}

    - name: Install GCC Compiler
      if: ${{ matrix.toolchain.build == 'fpm' }}
      uses: fortran-lang/setup-fortran@v1
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}

    - name: Install Intel Compiler (Linux)
      if: ${{ matrix.toolchain.build == 'fpm' }}
      uses: fortran-lang/setup-fortran@v1
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}

    - name: Install Intel MKL
      if: ${{ matrix.toolchain.build == 'fpm' }}
      run: |
        sudo apt-get install intel-oneapi-mkl-${{ matrix.toolchain.mkl_version }} intel-oneapi-mkl-devel-${{ matrix.toolchain.mkl_version }}

    - name: Setup Intel oneAPI environment
      if: ${{ matrix.toolchain.build == 'fpm' }}
      run: |
        source /opt/intel/oneapi/setvars.sh --force
        printenv >> $GITHUB_ENV

    - name: Setup environment for Fortran and C compilers
      run: |
        if [ ! -n "$FC" ]; then
          if [ "${{ matrix.toolchain.compiler }}" = "gcc" ]; then
            FC="gfortran"
            CC="gcc"
            CXX="g++"
          elif [ "${{ matrix.toolchain.compiler }}" = "intel" ]; then
            FC="ifx"
            CC="icx"
            CXX="icpx"
          elif [ "${{ matrix.toolchain.compiler }}" = "intel-classic" ]; then
            FC="ifort"
            CC="icc"
            CXX="icpc"
          fi
          echo "FC=$FC" >> $GITHUB_ENV
          echo "CC=$CC" >> $GITHUB_ENV
          echo "CXX=$CXX" >> $GITHUB_ENV
        fi

    - name: Install build and test dependencies
      if: ${{ ! contains(matrix.os, 'windows') }}
      run: pip3 install ${{ env.PIP_PACKAGES }} ${{ env.PIP_EXTRAS }}

    - name: Build library (fpm)
      if: ${{ matrix.toolchain.build == 'fpm' }}
      run: |
        FPM_CXXFLAGS=-DW_MKL
        echo "FPM_CXXFLAGS=$FPM_CXXFLAGS" >> $GITHUB_ENV
        fpm --version
        fpm build

    - name: Run unit tests (fpm)
      if: ${{ matrix.toolchain.build == 'fpm' }}
      run: fpm test

    - name: Create coverage report
      if: ${{ matrix.toolchain.build == 'meson' && matrix.build-type == 'coverage' }}
      run:
         ninja -C ${{ env.BUILD_DIR }} coverage

    - name: Install project
      if: ${{ matrix.toolchain.build != 'fpm' }}
      run: |
        ninja -C ${{ env.BUILD_DIR }} install
        echo "TBLITE_PREFIX=$PWD/_dist" >> $GITHUB_ENV
